spring:
  profiles:
    include: mysql
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  messages:
    basename: messages,errors

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB

file:
  path: /Users/gyuray/dev/projects/forum/src/main/resources/files/


#p6spy - sql insert문 조회
decorator:
  datasource:
    p6spy:
      enable-logging: true

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

