spring:
  profiles:
    include: mysql

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html