spring:
  profiles:
    include: mysql
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#p6spy - sql insert문 조회
decorator:
  datasource:
    p6spy:
      enable-logging: true

logging.level:
  org.hibernate.SQL: debug

